### ISSUE TITLE
"List" field type does not work (displays serialized version of output)

### ISSUE THREAD

**Issue by jgryn** [13pixlar/gravity-forms-sticky-form#3]
When using GravityForm's "List" advanced field type (I tested with "multiple columns") with sticky form, upon reloading the form, it appears that the the serialized version of the result shows up instead of what should be there.

For example, I see "a" ":" "1" ":"

**Comment by 13pixlar** [comment]
Thanks for reporting. What if you use list but NOT with multiple columns?

**Comment by jgryn** [comment]
The problem only starts when clicking "Enable multiple columns".

So to recap.
List field single column ("Enable Multiple Columns" NOT checked) WORKS OK
List field single column ("Enabled Multiple Columns" IS checked) IS BROKEN
List field 2 or more column ("Enabled Multiple Columns" IS checked) IS BROKEN

On a related note, I should first note, that this is a great plugin and we
do appreciate the work put into it.

I have a deliverable for a client that I'd prefer to use list fields with
multiple columns, we can re-build our forms to avoid multi column list
fields, but would just like to know an ETA for a fix so I can weigh than in
to whether or not we should rebuild the long forms.

**Comment by jgryn** [comment]
Not sure if it's relevant to this or not, but the latest gravity forms 1.9.10 has the following API updates:

Fixed an issue with exporting entries and the list type Custom field not outputting it's value correctly.
Fixed notices caused by new primary column parameter for classes extending the WP_List_Table class.

Added get_list_field_value( $entry, $field_id, $field ); Returns a comma separated string for the specified column or when multiple columns are not enabled.

Updated get_field_value() to use get_list_field_value().
Updated get_field_map_choices() and get_form_fields_as_choices() to include the List fields individual columns.

**Comment by jgryn** [comment]
Hi,  I wrote a few lines of code that seems to fix the issue.  I've tested it on all kinds of lists (both multiple and non-multiple columns checked, and within "multiple" both single and multiple actual columns in use).  The downside I've found so far is that if a new column is added after entries are made, the positions of the datum within the list fields become out of sync as they are filled Left to Right, Top Down.

The gist of what I did is as follows.  In sticky_pre_populate_the_form(), I check if a field is serialized, if so, I check if it contains an array within an array.  If so, just unravel the array into a single dimension before putting into $form_fields.

I added the following function to check for serialization just before sticky_pre_populate_the_form():
// from php.net unserialize documentation page
function isSerialized($str) 
{
    return ($str == serialize(false) || @unserialize($str) !== false);
}

Then after  unset($form_fields[$key]) and before // If we have an upload field, I add the following code:

```
                            if(isSerialized($value))
                            {
                                    $dump=unserialize($value);
                                    foreach($dump as $k => &$v)
                                    {
                                            if(is_array($v))
                                            {
                                                    unset($form_fields[$new_key]);
                                                    foreach($v as $k2 => &$v2)
                                                    {
                                                            $a[]=$v2;
                                                    }
                                                    $form_fields[$new_key]=$a;
                                            }
                                    }
                                    unset($a);
                            }
```

**Comment by 13pixlar** [comment]
Thats nice! Thanks for this. Would you mind issuing a pull request?

**Comment by jgryn** [comment]
Hi.  Happy to do this, but not sure how, new to github.  Do I need to branch the project or can I just post the file?

**Comment by 13pixlar** [comment]
Thanks for the pull request. It's now been merged into master.
